version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./logs/backend:/app/logs
    ports:
      - "5454:5454"
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5555:5555"
    depends_on:
      - backend
