version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5454:5454"
    volumes:
      - ./backend/app:/code/app
      - ./logs/backend:/code/logs

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./logs/frontend:/var/log/nginx

volumes:
  backend-logs:
  frontend-logs:
