version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5454:5454"
    volumes:
      - ./backend/app:/code/app
      - ./logs/backend:/code/logs
    environment:
      - MODULE_NAME=app.main
      - VARIABLE_NAME=app
      - PORT=5454

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5454:80" # Если вы хотите, чтобы фронтенд был доступен на том же порту, что и бэкенд
    volumes:
      - ./logs/frontend:/var/log/nginx

volumes:
  backend-logs:
  frontend-logs:
